### ISSUE TITLE
Namespaces for Part 9

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-100WG#8]
S-100WG7 Decisions and Actions says, in connection with agenda item WG7 4.19:
_[Decision 7/23] S-100WG approved in principle the proposal to fix namespace issues in XSD and XML files used for portrayal and finalize it at the TSM March 2023.
[Action 7/28] SevenCs, NIWC, T-CARIS, IIC to work further and submit a change proposal at the next TSM9 meeting._

I see no follow-up proposal or paper among the TSM9 documents and no decision about this in the TSM9 decisions/actions.

It is easy to add namespaces to portrayal schemas that don't have them.  Applying the consequences to portrayal files and portrayal catalogues might not be so easy.  Given that there is no approved change proposal at this time, I will have to hold off on applying the original proposal to the 5.1 schemas.  I can add namespaces relatively quickly - but would first need consensus as well as a go-ahead from WG leadership to apply it in the absence of an approved proposal.

_[Clarification: I have added namespaces in my local setup but would need consensus to having namespaces and a go-ahead before distributing the schemas with namespaces.]_

@TDYCARHugh
@HolgerBothien
@DavidGrant-NIWC
@kusala9

**Comment by DavidGrant-NIWC** [comment]
[S-100WG7-4.19](https://iho.int/uploads/user/Services%20and%20Standards/S-100WG/S-100WG7/S100WG7-4.19_2022_EN_Schema%20Use%20in%20Presentation%20Library%20XML%20and%20XSD%20files.pdf)

* We had no issue with the changes proposed in the paper.
* Are there changes required that are not spelled out in the paper?
  * If not, they just need to be copied to a change proposal form.
* These changes should be incorporated prior to S-101 2.0 so that the catalogs can be updated as needed.

> Applying the consequences to portrayal files and portrayal catalogues might not be so easy.

It shouldn't be that difficult, and either way it will need to be done at some point. Better now to maximize the time available for implementation / evaluation / testing.

**Comment by TDYCARHugh** [comment]
Agree with David. It would be good to get something, even draft, so we can see whether there are issues to resolve.

**Comment by rmalyankar** [comment]
The word I have from J.P. is that we can't make the change until we have a true proposal.

As I wrote earlier, I would need consensus and a go-ahead from WG leadership to distribute it in 5.1, in the absence of an approved proposal.  Also, time for 5.1 is getting short.

**Comment by DavidGrant-NIWC** [comment]
[Schema use in Presentation Library XSD files.docx](https://github.com/iho-ohi/S-100WG/files/11151361/Schema.use.in.Presentation.Library.XSD.files.docx)

I put Holgers name on the proposal because I just copied everything from his paper.

**Comment by HolgerBothien** [comment]
Thank you Dave.

**Comment by HolgerBothien** [comment]
Please note that in the proposal the namespace still ends with 5.0. The actual values must be according to the target version of S-100.

**Comment by DavidGrant-NIWC** [comment]
If everyone is good with the proposal, suggest that @HolgerBothien go ahead and send it to IHO for approval at the next WG.

**Comment by HolgerBothien** [comment]
Done

**Comment by rmalyankar** [comment]
Applied - staging.s100dev.net. Somebody will circulate information to the WG about reviewing.
